language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: identixone
  password:
    secure: X/bxoRBtNOUBn0nu6KUOypH6yWQpxAN8wtsPONqp19D8FrHeB28KWzgH9XJxsWJx5az7K+yFvj7BE8qc2PC6b2D1nMZDjAgf7sYPK7vEEX7+VSsp74gwjniNEznHZ+6ENSDGGUMOpan8s2KzNyXenYupQBUz9jmKAuQhtnELUjjWTeVzyNMp9FRtSLYziX1lj0cIPBI237CUMOzbKAAw8nG1oi0eMQ+JZHypSkFd0kGe50rTnABuwVcWwN5+03qUA3tusS+L1PcOb7JfnbFj7B8rYwryeP9Ht7KLAyUHTlGFqeuCKeEcWb8XaU811eXhIC5yyir2WfH1turT0jcB1SM6bkeybWAot2EHO4+USZ8gRvuSTT8W2k0QAfwQ0GcnIadBQRw8z7zWhOLwjJtL8H7qt9gt4UgdIwu503OgjtddE6ZayAkE+fF4g8h8ylfztOIDwUfV+Om4WmjCoKlXKNCE60gTigmu7ad3ZVeh7qrD9LIzUiiNiin7/0k1Uo4yG05cpfnuS9KSLGBJqqleP5zL7Ixiz3Je3E5GDie3x20fsd+L3sW4p9QZZP0s5z6YN7HlwxNzk/yij9MzWGNXLGQ4igiZj4DZOMpYB4lFXr16dKSowzLlCCqtiJBindFZ1L7jKBWF6BPXPEPIeSEt+Zv2xJlJDzLRgct8rys7g6o=
  on:
    tags: true
    repo: identixone/identixone
    python: 3.6
